#!/bin/sh

set -xe

apt-get update
yes | apt-get install make git openssh-client bash strace patch
# Install Xdebug and development specific configuration
docker-php-dev-mode xdebug
docker-php-dev-mode config
