#!/bin/sh

set -xe

apt-get update
yes | apt-get install  libfreetype6-dev libjpeg62-turbo-dev libpng-dev libvips-dev $PHPIZE_DEPS
## Initially this was an if statement to check for PHP 7.4, but since then the situation change so we're just going to try both to avoid the conditional growing out of hand
(docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ || docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/)
docker-php-ext-install -j$(nproc) gd
pecl install vips
docker-php-ext-enable vips
rm -rf /var/cache/apt/*
rm -rf /tmp/*
