ignored:
  - DL3018 # Pin versions in apk add - See: https://github.com/hadolint/hadolint/wiki/DL3018
  - SC2086 # For now I had troubles to do a proper quoting for PHPIZE_DEPS - See: https://github.com/koalaman/shellcheck/wiki/SC2086
  - DL3017 # For upgrading CVEs we need to use upgrade
  - SC2046
  - DL3022
  - DL3019
  - SC2006
  - DL3013 # So we can install the latest docker-compose