# syntax=docker/dockerfile:experimental
FROM php:7.4-cli-alpine3.11 AS base

# Build-time metadata as defined at http://label-schema.org
LABEL org.label-schema.name="wyrihaximusnet/php" \
      org.label-schema.description="Opinionated ReactPHP optimised PHP Docker images" \
      org.label-schema.url="https://github.com/wyrihaximusnet/docker-php" \
      org.label-schema.vcs-url="https://github.com/wyrihaximusnet/docker-php" \
      org.label-schema.vendor="WyriHaximus.net" \
      org.label-schema.schema-version="1.0"

RUN apk update \
    && set -x \
    && addgroup -g 1000 app \
    && adduser -u 1000 -D -G app app \
    && touch /.you-are-in-a-wyrihaximus.net-php-docker-image

FROM base AS base-build
RUN apk add --no-cache $PHPIZE_DEPS git libuv-dev

FROM base-build AS build-uv
RUN git clone https://github.com/bwoebi/php-uv uv
WORKDIR /uv
RUN git fetch \
    && git pull \
    && phpize \
    && ./configure \
    && make install \
    && EXTENSION_DIR=`php-config --extension-dir 2>/dev/null` && \
    cp "$EXTENSION_DIR/uv.so" /uv.so
RUN sha256sum /uv.so

FROM base AS nts-slim-root

COPY --from=build-uv /uv.so /uv.so

# Patch CVE-2018-14618 (curl), CVE-2018-16842 (libxml2), CVE-2019-1543 (openssl)
RUN apk upgrade --no-cache curl libxml2 openssl

# Install docker help scripts
COPY src/php/utils/docker/ /usr/local/bin/

COPY src/php/conf/ /usr/local/etc/php/conf.d/
COPY src/php/cli/conf/*.ini /usr/local/etc/php/conf.d/

RUN EXTENSION_DIR=`php-config --extension-dir 2>/dev/null` && \
	mv /*.so "$EXTENSION_DIR/" && \
	apk add --no-cache \
        gmp-dev \
        zlib-dev \
        postgresql-dev \
        libzip-dev \
        libuv-dev \
        coreutils \
        procps \
        git \
        $PHPIZE_DEPS \
    ## Install PECL
    && wget pear.php.net/go-pear.phar && php go-pear.phar \
    && docker-php-ext-install -j$(nproc) pcntl pgsql pdo pdo_pgsql bcmath zip gmp iconv opcache \
    && docker-php-ext-enable uv \
    && apk del $PHPIZE_DEPS \
    && wget -O - https://raw.githubusercontent.com/eficode/wait-for/master/wait-for > /bin/wait-for \
    && chmod +x /bin/wait-for \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/*

# Install shush
COPY src/php/utils/install-shush /usr/local/bin/
RUN install-shush && rm -rf /usr/local/bin/install-shush

STOPSIGNAL SIGTERM

ENTRYPOINT ["/usr/local/bin/shush", "exec", "docker-php-entrypoint"]

## NTS-DEV STAGE ##
FROM nts-slim-root AS nts-root

# Install ext-gd and ext-vips
COPY src/php/utils/docker/alpine/install-gd-and-vips /usr/local/bin/install-gd-and-vips
RUN install-gd-and-vips && rm -rf /usr/local/bin/install-gd-and-vips

## NTS-DEV STAGE ##
FROM nts-slim-root AS nts-slim-dev-root

RUN touch /.you-are-in-a-wyrihaximus.net-php-docker-image-dev

# Install docker help scripts
COPY src/php/utils/docker/alpine/dev-mode /usr/local/bin/dev-mode
COPY src/php/utils/docker/alpine/docker-php-dev-mode /usr/local/bin/docker-php-dev-mode
RUN dev-mode && rm -rf /usr/local/bin/dev-mode && rm -rf /usr/local/bin/docker-php-dev-mode

# Install composer
COPY src/php/utils/install-composer /usr/local/bin/
RUN install-composer && rm -rf /usr/local/bin/install-composer

# Change entrypoint back to the default because we don't need shush in development
ENTRYPOINT ["docker-php-entrypoint"]

## NTS-DEV STAGE ##
FROM nts-root AS nts-dev-root

RUN touch /.you-are-in-a-wyrihaximus.net-php-docker-image-dev

# Install docker help scripts
COPY src/php/utils/docker/alpine/dev-mode /usr/local/bin/dev-mode
COPY src/php/utils/docker/alpine/docker-php-dev-mode /usr/local/bin/docker-php-dev-mode
RUN dev-mode && rm -rf /usr/local/bin/dev-mode && rm -rf /usr/local/bin/docker-php-dev-mode

# Install composer
COPY src/php/utils/install-composer /usr/local/bin/
RUN install-composer && rm -rf /usr/local/bin/install-composer

# Change entrypoint back to the default because we don't need shush in development
ENTRYPOINT ["docker-php-entrypoint"]

## NTS-DEV stage ##
FROM nts-slim-dev-root AS nts-slim-dev
USER app

FROM nts-dev-root AS nts-dev
USER app

## NTS stage ##
FROM nts-slim-root AS nts-slim
USER app

FROM nts-root AS nts
USER app
