# syntax=docker/dockerfile:experimental
ARG PHP_VERSION=7.4
ARG OS_VERSION=alpine3.11
FROM php:$PHP_VERSION-zts-$OS_VERSION AS base
ARG ARCH=amd64
ARG PHP_VERSION=7.4
ARG OS_VERSION=alpine3.11
ENV PHP_VERSION=$PHP_VERSION
ENV OS_VERSION=$OS_VERSION

# Build-time metadata as defined at http://label-schema.org and https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
LABEL org.label-schema.title="Opinionated ReactPHP optimised PHP Docker images" \
      org.label-schema.description="PHP Version: $PHP_VERSION Type: zts OS Version: $OS_VERSION" \
      org.label-schema.url="https://github.com/wyrihaximusnet/docker-php" \
      org.label-schema.vcs-url="https://github.com/wyrihaximusnet/docker-php" \
      org.label-schema.vendor="WyriHaximus.net" \
      org.label-schema.schema-version="1.0" \
      org.opencontainers.image.source="https://github.com/wyrihaximusnet/docker-php" \
      org.opencontainers.image.url="https://github.com/wyrihaximusnet/docker-php" \
      org.opencontainers.image.documentation="https://github.com/wyrihaximusnet/docker-php" \
      org.opencontainers.image.title="Opinionated ReactPHP optimised PHP Docker images" \
      org.opencontainers.image.description="PHP Version: $PHP_VERSION Type: zts OS Version: $OS_VERSION" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.base.name="php:$PHP_VERSION-zts-$OS_VERSION" \
      org.opencontainers.image.vendor="WyriHaximus.net" \
      org.opencontainers.image.authors="Cees-Jan Kiewiet <docker-php@ceesjankiewiet.nl>"

RUN apk update \
    && apk upgrade \
    && set -x \
    && addgroup -g 1000 app \
    && adduser -u 1000 -D -G app app --home /opt/app \
    && touch /.you-are-in-a-wyrihaximus.net-php-docker-image

COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

FROM base AS base-build
RUN apk add --no-cache $PHPIZE_DEPS git libuv-dev

FROM base-build AS build-uv
RUN git clone https://github.com/amphp/ext-uv uv
WORKDIR /uv
RUN git fetch \
    && git pull \
    && phpize \
    && ./configure \
    && make install \
    && EXTENSION_DIR=`php-config --extension-dir 2>/dev/null` \
    && cp "$EXTENSION_DIR/uv.so" /uv.so \
    && sha256sum /uv.so

FROM base AS zts-slim-root

COPY --from=build-uv /uv.so /uv.so

# Install docker help scripts
COPY src/php/utils/docker/alpine/ /usr/local/bin/

COPY src/php/conf/ /usr/local/etc/php/conf.d/
COPY src/php/cli/conf/*.ini /usr/local/etc/php/conf.d/
COPY src/php/conf/available/prod.ini /usr/local/etc/php/conf.d/zzz_prod.ini

COPY --from=ghcr.io/php/pie:1.2.1-bin /pie /usr/bin/pie

RUN EXTENSION_DIR=`php-config --extension-dir 2>/dev/null` && \
  rm /usr/local/etc/php/conf.d/jit.ini && \
	mv /*.so "$EXTENSION_DIR/" && \
	apk add --no-cache \
        libuv-dev \
        zlib-dev  \
        icu-dev \
        libevent-dev \
        openssl-dev \
        make \
        git \
        openssh-client \
        bash \
        coreutils \
        procps \
        git \
        $PHPIZE_DEPS \
    ## Install PECL
    && wget -q pear.php.net/go-pear.phar && php go-pear.phar \
    && install-php-extensions pcntl pgsql pdo pdo_pgsql bcmath zip gmp iconv opcache intl sockets ffi opentelemetry \
    && if [ $(php -v | grep "PHP 8.5" | wc -l) != 0 ] ; then true ; else install-php-extensions grpc; fi \
    && (install-php-extensions random || true) \
    && pecl install parallel || pecl install parallel-1.1.4 \
    && docker-php-ext-enable parallel \
    && (pecl install eio || pecl install eio-beta) \
    && docker-php-ext-enable eio \
    && pecl install event \
    # To ensure ext-socket loads before ext-event
    && docker-php-ext-enable --ini-name zzzzz-event.ini event \
    && docker-php-ext-enable uv \
    && apk del $PHPIZE_DEPS \
    && wget -q -O - https://raw.githubusercontent.com/eficode/wait-for/master/wait-for > /bin/wait-for \
    && chmod +x /bin/wait-for \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/*

STOPSIGNAL SIGTERM

ENTRYPOINT ["docker-php-entrypoint"]

## ZTS-DEV STAGE ##
FROM zts-slim-root AS zts-root

# Install ext-gd and ext-vips
COPY src/php/utils/docker/alpine/install-gd-and-vips /usr/local/bin/install-gd-and-vips
RUN if [ $(php -v | grep "alpha\|ALPHA\|beta\|BETA\|rc\|RC" | wc -l) != 0 ] ; then true ; else install-gd-and-vips; fi \
     && rm -rf /usr/local/bin/install-gd-and-vips

## ZTS-DEV STAGE ##
FROM zts-slim-root AS zts-slim-dev-root

RUN touch /.you-are-in-a-wyrihaximus.net-php-docker-image-dev

# Install docker help scripts
COPY src/php/utils/docker/alpine/dev-mode /usr/local/bin/dev-mode
RUN if [ $(php -v | grep "alpha\|ALPHA\|beta\|BETA\|rc\|RC" | wc -l) != 0 ] ; then true ; else dev-mode; fi && rm -rf /usr/local/bin/dev-mode

# Install composer
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer


ENTRYPOINT ["docker-php-entrypoint"]

## ZTS-DEV STAGE ##
FROM zts-root AS zts-dev-root

RUN touch /.you-are-in-a-wyrihaximus.net-php-docker-image-dev

# Install docker help scripts
COPY src/php/utils/docker/alpine/dev-mode /usr/local/bin/dev-mode
RUN if [ $(php -v | grep "alpha\|ALPHA\|beta\|BETA\|rc\|RC" | wc -l) != 0 ] ; then true ; else dev-mode; fi && rm -rf /usr/local/bin/dev-mode

# Install composer
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer


ENTRYPOINT ["docker-php-entrypoint"]

## ZTS-DEV stage ##
FROM zts-slim-dev-root AS zts-slim-dev
USER app

FROM zts-dev-root AS zts-dev
USER app

## ZTS stage ##
FROM zts-slim-root AS zts-slim
USER app

FROM zts-root AS zts
USER app
