name: Continuous Integration
env:
  DOCKER_IMAGE: wyrihaximusnet/php
  DOCKER_BUILDKIT: 1
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '33 */4 * * *'
jobs:
  generate-alpine-strategy:
    name: Generate Alpine
    runs-on: ubuntu-latest
    container:
      image: wyrihaximusnet/php:7.4-nts-alpine3.12-root
    outputs:
      alpine: ${{ steps.generate-alpine-strategy.outputs.versions }}
    steps:
      - uses: actions/checkout@v1
      - id: generate-alpine-strategy
        name: Generate Alpine
        uses: wyrihaximus/github-action-supported-alpine-linux-versions@v1
  generate-php-strategy:
    name: Generate PHP
    runs-on: ubuntu-latest
    outputs:
      php: ${{ steps.generate-php-strategy.outputs.versions }}
    steps:
      - uses: actions/checkout@v1
      - id: generate-php-strategy
        name: Generate PHP
        uses: wyrihaximus/github-action-supported-php-versions@v1
  generate-type-strategy:
    name: Generate Type
    runs-on: ubuntu-latest
    outputs:
      type: ${{ steps.generate-type-strategy.outputs.type }}
    steps:
      - uses: actions/checkout@v1
      - id: generate-type-strategy
        name: Generate Type
        run: |
          echo "::set-output name=type::[\"zts\", \"nts\"]"
  generate-combined-strategy:
    name: Generate Combined
    runs-on: ubuntu-latest
    needs:
      - generate-alpine-strategy
      - generate-php-strategy
    outputs:
      image: ${{ steps.generate-combined-strategy.outputs.image }}
    steps:
      - uses: actions/checkout@v1
      - id: generate-combined-strategy
        name: Generate Combined
        run: |
          if [ "${{ github.event_name }}" == "schedule" ] ; then
            php utils/newer-upstream-images.php
            exit 0
          fi

          php utils/all-images.php
        env:
          ALPINE: ${{ needs.generate-alpine-strategy.outputs.alpine }}
          PHP: ${{ needs.generate-php-strategy.outputs.php }}
  lint:
    runs-on: ubuntu-latest
    needs:
      - generate-type-strategy
    strategy:
      fail-fast: false
      matrix:
        type: ${{ fromJson(needs.generate-type-strategy.outputs.type) }}
    steps:
      - uses: actions/checkout@v2
      - name: Lint ${{ matrix.type }}
        uses: docker://hadolint/hadolint:latest-debian
        with:
          entrypoint: hadolint
          args: Dockerfile-${{ matrix.type }}
  build:
    needs:
      - lint
      - generate-combined-strategy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-combined-strategy.outputs.image) }}
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ./docker-image/
      - run: ./build-php.sh $(echo "${{ matrix.image }}" | tr '-' ' ')
      - run: cat ./docker-image/image.tags | xargs -I % docker inspect --format='%={{.Id}}:{{index .Config.Env 7}}' %
      - run: docker save "${DOCKER_IMAGE}" | gzip -9 > ./docker-image/image.tar
      - run: docker images
      - name: Upload Images (attempt #1)
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ matrix.image }}
          path: ./docker-image
      - name: Upload Images (attempt #2)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ matrix.image }}
          path: ./docker-image
      - name: Upload Images (attempt #3)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ matrix.image }}
          path: ./docker-image
  scan-vulnerability:
    needs:
      - build
      - generate-combined-strategy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-combined-strategy.outputs.image) }}
    steps:
      - uses: actions/checkout@v2
      - name: Install clair-scanner
        run: |
          sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 -o /usr/local/bin/clair-scanner
          sudo chmod +x /usr/local/bin/clair-scanner
      - name: Download Images
        uses: actions/download-artifact@v2
        with:
          name: docker-image-${{ matrix.image }}
          path: ./docker-image
      - run: docker load --input ./docker-image/image.tar
      - run: mkdir -p "./clair/${DOCKER_IMAGE}"
      - run: make ci-scan-vulnerability
  test:
    needs:
      - build
      - generate-combined-strategy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-combined-strategy.outputs.image) }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Images
        uses: actions/download-artifact@v2
        with:
          name: docker-image-${{ matrix.image }}
          path: ./docker-image
      - run: ls -lasth ./docker-image
      - run: docker load --input ./docker-image/image.tar
      - run: make $(php -r 'echo "test-", explode("-", str_replace(["zts-zts", "cli-nts"], ["zts", "nts"], "${{ matrix.image }}"))[0];')
      - run: rm -Rf ./docker-image/
  push:
    if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/master'
    needs:
      - scan-vulnerability
      - test
      - generate-combined-strategy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.generate-combined-strategy.outputs.image) }}
    steps:
      - uses: actions/checkout@v2
      - name: Download Images
        uses: actions/download-artifact@v2
        with:
          name: docker-image-${{ matrix.image }}
          path: ./docker-image
      - run: docker load --input ./docker-image/image.tar
      - run: make ci-push
        env:
          DOCKER_USER: ${{ secrets.HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.HUB_PASSCODE }}
