name: Clean up untagged versions
on:
  workflow_dispatch:
  schedule:
    - cron:  "13 0 * * *"
jobs:
  clean-up-untagged-images:
    name: Clean up untagged versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          owner: "wyrihaximusnet"
          package-name: "php"
          package-type: "container"
          delete-only-untagged-versions: "true"
